-- Stack n Stock Inventory OS V9 rebuild schema
-- Safe to run multiple times. Existing data is not deleted.
create extension if not exists pgcrypto;

create table if not exists public.inventory_items (id text primary key, item_code text unique not null, description text default '', uom text default 'Nos', category text default '', qty numeric default 0, bin text default '', supplier text default '', status text default 'OK', created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists public.bin_locations (id text primary key, bin_id text unique not null, status text default 'Inactive', current_qty numeric default 0, zone text default '', rack text default '', remarks text default '', created_at timestamptz default now());
create table if not exists public.quarantine_items (id text primary key, item_code text not null, description text default '', uom text default '', qty numeric default 0, status text default 'HOLD', source_doc_no text default '', remarks text default '', created_at timestamptz default now());
create table if not exists public.stock_ledger (id text primary key, ledger_date date default current_date, movement_type text not null, source_doc_type text default '', source_doc_no text default '', source_line_id text default '', item_id text default '', item_code text not null, description text default '', uom text default '', in_qty numeric default 0, out_qty numeric default 0, from_bin text default '', to_bin text default '', location_status text default 'OK', work_order text default '', department text default '', vendor text default '', qty_before numeric default 0, qty_after numeric default 0, unit_cost numeric default 0, total_value numeric default 0, remarks text default '', created_by uuid, created_by_email text default '', created_at timestamptz default now());
create table if not exists public.grn_headers (id text primary key, grn_no text unique not null, grn_date date default current_date, po_no text default '', supplier text default '', invoice_no text default '', dc_no text default '', received_by text default '', qc_status text default 'PENDING', remarks text default '', created_by uuid, created_by_email text default '', created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists public.grn_lines (id text primary key, grn_id text references public.grn_headers(id) on delete cascade, item_code text not null, description text default '', uom text default '', ordered_qty numeric default 0, received_qty numeric default 0, accepted_qty numeric default 0, rejected_qty numeric default 0, hold_qty numeric default 0, putaway_bin text default '', unit_rate numeric default 0, landed_cost numeric default 0, qc_status text default 'PENDING', remarks text default '', created_at timestamptz default now());
create table if not exists public.miv_headers (id text primary key, miv_no text unique not null, miv_date date default current_date, source_ticket_no text default '', issued_from text default '', issued_to text default '', department text default '', work_order text default '', issue_type text default 'PRODUCTION', return_expected text default 'N', expected_return_date date, issued_by text default '', received_by text default '', status text default 'ISSUED', remarks text default '', created_by uuid, created_by_email text default '', created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists public.miv_lines (id text primary key, miv_id text references public.miv_headers(id) on delete cascade, item_id text default '', item_code text not null, description text default '', uom text default '', from_bin text default '', qty_requested numeric default 0, qty_issued numeric default 0, remarks text default '', created_at timestamptz default now());
create table if not exists public.mrn_headers (id text primary key, mrn_no text unique not null, mrn_date date default current_date, source_doc_no text default '', returned_by text default '', good_qty numeric default 0, scrap_qty numeric default 0, status text default 'RECORDED', remarks text default '', created_by uuid, created_by_email text default '', created_at timestamptz default now());
create table if not exists public.mrn_lines (id text primary key, mrn_id text references public.mrn_headers(id) on delete cascade, source_doc_no text default '', source_line_id text default '', item_code text not null, description text default '', uom text default '', good_qty numeric default 0, scrap_qty numeric default 0, to_bin text default '', remarks text default '', created_at timestamptz default now());
create table if not exists public.delivery_challans (id text primary key, dc_no text unique not null, dc_date date default current_date, linked_job_work_no text default '', vendor text default '', vendor_address text default '', vendor_gstin text default '', purpose text default 'JOB_WORK', returnable text default 'Y', expected_return_date date, vehicle_no text default '', transporter text default '', eway_bill_no text default '', approx_value numeric default 0, status text default 'OPEN', remarks text default '', created_by uuid, created_by_email text default '', created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists public.delivery_challan_lines (id text primary key, dc_id text references public.delivery_challans(id) on delete cascade, item_code text not null, description text default '', hsn_sac text default '', uom text default '', qty numeric default 0, rate numeric default 0, value numeric default 0, remarks text default '', created_at timestamptz default now());
create table if not exists public.job_work_headers (id text primary key, job_work_no text unique not null, date_sent date default current_date, vendor text default '', delivery_challan_no text default '', expected_return_date date, process_instruction text default '', status text default 'OPEN', vendor_invoice_no text default '', job_charges numeric default 0, transport_cost numeric default 0, gst_amount numeric default 0, remarks text default '', created_by uuid, created_by_email text default '', created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists public.job_work_lines (id text primary key, job_work_id text references public.job_work_headers(id) on delete cascade, source_item_code text not null, source_description text default '', source_uom text default '', qty_sent numeric default 0, output_item_code text default '', output_description text default '', qty_received numeric default 0, wastage_qty numeric default 0, qc_status text default 'PENDING', remarks text default '', created_at timestamptz default now());
create table if not exists public.wip_conversions (id text primary key, wip_no text unique not null, start_date date default current_date, completion_date date, work_order text default '', process_name text default '', output_item_code text not null, output_description text default '', output_uom text default '', output_qty numeric default 0, labour_cost numeric default 0, consumables_cost numeric default 0, status text default 'IN_PROGRESS', remarks text default '', created_by uuid, created_by_email text default '', created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists public.wip_conversion_lines (id text primary key, wip_id text references public.wip_conversions(id) on delete cascade, input_item_code text not null, input_description text default '', input_uom text default '', qty_used numeric default 0, unit_cost numeric default 0, total_value numeric default 0, remarks text default '', created_at timestamptz default now());
create table if not exists public.scrap_register (id text primary key, scrap_no text unique not null, scrap_date date default current_date, source_doc_type text default '', source_doc_no text default '', item_code text not null, description text default '', uom text default '', qty_scrapped numeric default 0, reason text default '', approved_by text default '', scrap_value numeric default 0, status text default 'RECORDED', remarks text default '', created_by uuid, created_by_email text default '', created_at timestamptz default now());
create table if not exists public.reorder_settings (id text primary key, item_code text unique not null, reorder_point numeric default 0, reorder_qty numeric default 0, enabled boolean default true, preferred_supplier text default '', lead_time_days numeric default 0, updated_by uuid, updated_at timestamptz default now());
create table if not exists public.item_cost_layers (id text primary key, item_code text not null, source_doc_type text default '', source_doc_no text default '', qty numeric default 0, unit_cost numeric default 0, total_value numeric default 0, cost_method text default 'ACTUAL', created_at timestamptz default now());
create table if not exists public.user_roles (id uuid primary key references auth.users(id) on delete cascade, email text not null, role text not null default 'viewer', department text default '', created_at timestamptz default now(), updated_at timestamptz default now());

create index if not exists idx_stock_ledger_item_code on public.stock_ledger(item_code);
create index if not exists idx_stock_ledger_doc on public.stock_ledger(source_doc_no);
create index if not exists idx_miv_lines_miv on public.miv_lines(miv_id);
create index if not exists idx_mrn_lines_source on public.mrn_lines(source_line_id);

create or replace function public.upper_item_code_fn() returns trigger as $$ begin new.item_code := upper(trim(new.item_code)); return new; end; $$ language plpgsql;
do $$ begin
  if not exists (select 1 from pg_trigger where tgname='trg_inventory_upper_item_code') then create trigger trg_inventory_upper_item_code before insert or update on public.inventory_items for each row execute function public.upper_item_code_fn(); end if;
  if not exists (select 1 from pg_trigger where tgname='trg_stock_ledger_upper_item_code') then create trigger trg_stock_ledger_upper_item_code before insert or update on public.stock_ledger for each row execute function public.upper_item_code_fn(); end if;
end $$;
